allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.60.0'
  - miniflare@5.20260923.0-alpha
  - wrangler@4.139.0
  - esbuild@0.25.12
  - image-size@2.0.3
overrides:
  esbuild@<=0.24.2: 0.25.12
  image-size@>=0.6.3 <=2.0.2: ^2.0.3
  image-size@>=1.2.0 <=2.0.2: ^2.0.3
