"use client";
import { useState } from 'react';
import './opening.css';
import { professionals } from './agenda/professionals';
import { WeeklySchedule } from './agenda/WeeklySchedule';
function Brand(){return <a className="brand" href="#inicio" aria-label="Clínica São Lucas — início"><img src="/logo-original.jpg" alt="" width="52" height="52"/><span><small>CLÍNICA</small><strong>SÃO LUCAS</strong></span></a>}
function Label({n,title,aside}:{n:string,title:string,aside:string}){return <div className="section-label"><span>{n} / {title}</span><span>{aside}</span></div>}
export default function Home(){const [menu,setMenu]=useState(false);return <>
<a className="skip" href="#conteudo">Pular para o conteúdo</a><header className="site-header"><Brand/><nav id="navigation" aria-label="Navegação principal" className={menu?'open':''}>{[['A clínica','clinica'],['Atendimentos','atendimentos'],['Profissionais','profissionais']].map(([text,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{text}</a>)}<a className="nav-contact" href="#contato" onClick={()=>setMenu(false)}>Fale conosco <span>↗</span></a></nav><button className="menu-toggle" aria-controls="navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Fechar −':'Menu +'}</button></header>
<main id="conteudo"><section className="hero" id="inicio"><div className="hero-top"><span className="eyebrow">BELÉM DE SÃO FRANCISCO · PE</span><span className="edition">Saúde com presença.</span></div><div className="hero-content"><div className="hero-copy"><h1>O cuidado<br/>que aproxima.<br/><em>A saúde que<br/>transforma.</em></h1><p>Diferentes especialidades. Um mesmo propósito:<br className="desktop-break"/> cuidar de você, mais perto de casa.</p><a className="button" href="#atendimentos">Conheça nossos atendimentos <span>↗</span></a></div><figure className="clinic-feature"><div className="clinic-feature-image"><img src="/clinica-fachada-referencia.png" alt="Fachada da Clínica São Lucas apresentada na referência" fetchPriority="high"/></div><figcaption><span className="eyebrow">CLÍNICA SÃO LUCAS</span><p>O seu cuidado.<br/><em>Mais perto de casa.</em></p><span className="clinic-location">Belém de São Francisco · PE</span></figcaption></figure></div><div className="hero-bottom"><a href="#clinica">Conheça a clínica <span>↓</span></a><span>Ciência. Escuta. Cuidado.</span></div></section>
<div className="ribbon"><span>Saúde em cada fase da vida</span><i>✳</i><span>Cuidado que conecta</span><i>✳</i><span>Clínica São Lucas</span><i>✳</i><span>Saúde em cada fase da vida</span></div>
<section className="about section" id="clinica"><Label n="01" title="A CLÍNICA" aside="PERTO DE VOCÊ"/><div className="about-grid"><div className="photo-placeholder"><span className="corner">CLÍNICA SÃO LUCAS</span><div className="placeholder-center"><span className="plus">+</span><p>Um espaço<br/>para acolher.</p></div><span className="photo-caption">FOTOGRAFIA DA CLÍNICA · EM BREVE</span></div><div className="about-copy"><h2>Antes de tudo,<br/>olhamos para<br/><em>você.</em></h2><p>A Clínica São Lucas está em Belém de São Francisco, Pernambuco. Aqui, diferentes áreas da saúde se encontram em um só lugar.</p><p className="provisional">[Texto institucional provisório]<br/>Este espaço receberá a história da clínica, sua estrutura e sua forma de cuidar.</p><a className="text-link" href="#contato">Vamos conversar <span>↗</span></a></div></div></section>
<WeeklySchedule professionals={professionals}/>
<section className="manifesto"><span className="eyebrow">NOSSA RAZÃO DE ESTAR AQUI</span><h2>Cuidar é estar perto.<br/><em>Em cada fase.</em><br/>Em cada recomeço.</h2><span className="manifesto-star" aria-hidden="true">✳</span><p>CLÍNICA SÃO LUCAS · BELÉM DE SÃO FRANCISCO</p></section>
<section className="team section" id="profissionais"><Label n="03" title="PROFISSIONAIS" aside="QUEM CUIDA DE VOCÊ"/><div className="team-grid"><h2>Muitos olhares.<br/><em>Um cuidado<br/>mais próximo.</em></h2><div className="team-copy"><p>Conheça os profissionais apresentados pela Clínica São Lucas.</p><div className="team-reserved"><span>NOSSA EQUIPE</span><p>As pessoas por trás<br/>de cada cuidado.</p><small>Consulte a clínica para confirmar a disponibilidade dos atendimentos.</small></div></div></div><div className="professionals-grid">{professionals.map(person=><figure className="professional" key={person.id}><div className="professional-photo"><img src={'/profissionais/'+person.id+'.webp'} alt={person.name} width="150" height="130" loading="lazy"/></div><figcaption><h3>{person.name}</h3><p>{person.area}</p></figcaption></figure>)}</div></section>
<section className="contact section" id="contato"><Label n="04" title="CONTATO" aside="VAMOS CONVERSAR"/><div className="contact-grid"><div><h2>Seu próximo passo<br/>começa com uma<br/><em>boa conversa.</em></h2><p>Informações sobre atendimentos e agendamentos<br/>com a equipe da Clínica São Lucas.</p><div className="contact-pending">WhatsApp <span>↗</span><small>[NÚMERO DA CLÍNICA A CONFIRMAR]</small></div></div><div className="contact-info"><div><span>ONDE ESTAMOS</span><h3>Belém de São Francisco — PE</h3><p>[ENDEREÇO COMPLETO DA CLÍNICA]</p></div><div><span>HORÁRIOS</span><p>[HORÁRIO DE FUNCIONAMENTO]</p></div><div><span>ACOMPANHE A CLÍNICA</span><p>Instagram · [PERFIL OFICIAL]</p></div><small>Os canais de contato serão ativados após a confirmação dos dados.</small></div></div></section></main>
<footer><Brand/><p>Cuidar de você. Perto de você.</p><a href="#inicio">Voltar ao topo ↑</a><div className="footer-bottom"><span>© 2026 Clínica São Lucas.</span><span>PRIMEIRA VERSÃO · CONTEÚDO EM VALIDAÇÃO</span></div></footer></>}
