"use client";
import { useState } from 'react';
const services = [
 ['Fisioterapia','Movimento & bem-estar','Cuidado com o movimento, a mobilidade e a qualidade de vida.','Dra. Giselle Skarlet'],
 ['Ginecologia e obstetrícia','Saúde da mulher','Atenção à saúde da mulher em diferentes fases da vida.','Dra. Ilka Gominho'],
 ['Nutrição','Alimentação & saúde','Orientação nutricional a partir das necessidades de cada pessoa.','Dra. Ítala Freire e Dra. Layane Barros'],
 ['Psicologia','Escuta & acolhimento','Um espaço de escuta e atenção à saúde emocional.','Maria Paula'],
 ['Fonoaudiologia','Comunicação & cuidado','Atenção à comunicação e às necessidades fonoaudiológicas.','Dra. Ariane Matos'],
 ['Outros atendimentos','Cuidado multidisciplinar','Gastroenterologia, pneumologia, psicopedagogia, procedimentos estéticos e exames laboratoriais.','Equipe e disponibilidade a confirmar']
];
const professionals = [
 {id:'joceane-ramos',name:'Joceane Ramos',area:'Procedimentos estéticos'},
 {id:'ariane-matos',name:'Dra. Ariane Matos',area:'Fonoaudiologia'},
 {id:'ilka-gominho',name:'Dra. Ilka Gominho',area:'Ginecologia e obstetrícia'},
 {id:'giselle-skarlet',name:'Dra. Giselle Skarlet',area:'Fisioterapia'},
 {id:'louise-torres',name:'Dra. Louise Torres',area:'Gastroenterologia'},
 {id:'itala-freire',name:'Dra. Ítala Freire',area:'Nutrição'},
 {id:'ermita-galdina',name:'Ermita Galdina',area:'Psicopedagogia e neuropsicopedagogia'},
 {id:'maria-paula',name:'Maria Paula',area:'Psicologia'},
 {id:'layane-barros',name:'Dra. Layane Barros',area:'Nutrição'},
 {id:'karina-hirose',name:'Dra. Karina Hirose',area:'Pneumologia'}
];
const servicePortraits = [['giselle-skarlet'],['ilka-gominho'],['itala-freire','layane-barros'],['maria-paula'],['ariane-matos'],['joceane-ramos','louise-torres','ermita-galdina','karina-hirose']];
function Brand(){return <a className="brand" href="#inicio" aria-label="Clínica São Lucas — início"><img src="/logo-original.jpg" alt="" width="52" height="52"/><span><small>CLÍNICA</small><strong>SÃO LUCAS</strong></span></a>}
function Label({n,title,aside}:{n:string,title:string,aside:string}){return <div className="section-label"><span>{n} / {title}</span><span>{aside}</span></div>}
export default function Home(){const [menu,setMenu]=useState(false);return <>
<a className="skip" href="#conteudo">Pular para o conteúdo</a><header><Brand/><nav id="navigation" aria-label="Navegação principal" className={menu?'open':''}>{[['A clínica','clinica'],['Atendimentos','atendimentos'],['Profissionais','profissionais']].map(([text,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{text}</a>)}<a className="nav-contact" href="#contato" onClick={()=>setMenu(false)}>Fale conosco <span>↗</span></a></nav><button className="menu-toggle" aria-controls="navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Fechar −':'Menu +'}</button></header>
<main id="conteudo"><section className="hero" id="inicio"><div className="hero-top"><span className="eyebrow">BELÉM DE SÃO FRANCISCO · PE</span><span className="edition">Saúde com presença.</span></div><div className="hero-content"><div className="hero-copy"><h1>O cuidado<br/>que aproxima.<br/><em>A saúde que<br/>transforma.</em></h1><p>Diferentes especialidades. Um mesmo propósito:<br className="desktop-break"/> cuidar de você, mais perto de casa.</p><a className="button" href="#atendimentos">Conheça nossos atendimentos <span>↗</span></a></div><figure className="hero-portrait"><div className="portrait-backdrop" aria-hidden="true"/><img src="/profissionais/louise-destaque.webp" alt="Dra. Louise Torres, profissional da Clínica São Lucas" width="777" height="1034" fetchPriority="high"/><figcaption><span>QUEM CUIDA DE VOCÊ</span><strong>Dra. Louise Torres</strong><small>Gastroenterologia</small></figcaption></figure></div><div className="hero-bottom"><a href="#clinica">Conheça a clínica <span>↓</span></a><span>Ciência. Escuta. Cuidado.</span></div></section>
<div className="ribbon"><span>Saúde em cada fase da vida</span><i>✳</i><span>Cuidado que conecta</span><i>✳</i><span>Clínica São Lucas</span><i>✳</i><span>Saúde em cada fase da vida</span></div>
<section className="about section" id="clinica"><Label n="01" title="A CLÍNICA" aside="PERTO DE VOCÊ"/><div className="about-grid"><div className="photo-placeholder"><span className="corner">CLÍNICA SÃO LUCAS</span><div className="placeholder-center"><span className="plus">+</span><p>Um espaço<br/>para acolher.</p></div><span className="photo-caption">FOTOGRAFIA DA CLÍNICA · EM BREVE</span></div><div className="about-copy"><h2>Antes de tudo,<br/>olhamos para<br/><em>você.</em></h2><p>A Clínica São Lucas está em Belém de São Francisco, Pernambuco. Aqui, diferentes áreas da saúde se encontram em um só lugar.</p><p className="provisional">[Texto institucional provisório]<br/>Este espaço receberá a história da clínica, sua estrutura e sua forma de cuidar.</p><a className="text-link" href="#contato">Vamos conversar <span>↗</span></a></div></div></section>
<section className="services section" id="atendimentos"><Label n="02" title="ATENDIMENTOS" aside="CUIDADO EM DIFERENTES DIMENSÕES"/><div className="section-heading"><h2>Sua saúde.<br/><em>Nosso ponto de encontro.</em></h2><p>Conheça os atendimentos presentes no material da clínica. Consulte a equipe para confirmar a disponibilidade.</p></div><div className="service-grid">{services.map(([name,area,text,person],i)=><article className="service" key={name}><div className={'service-visual visual-'+i} aria-hidden="true"><span>{String(i+1).padStart(2,'0')}</span><i>✳</i><div className={'service-portraits portraits-'+servicePortraits[i].length}>{servicePortraits[i].map(id=><img key={id} src={'/profissionais/'+id+'.webp'} alt="" loading="lazy"/>)}</div></div><span className="eyebrow">{area}</span><h3>{name}</h3><p>{text}</p><details><summary>Sobre o atendimento <span>+</span></summary><div className="service-detail"><p>{person}</p><p>Informações com base na arte enviada. Datas, horários e escopo do atendimento a confirmar.</p><a href="#contato">Consultar informações ↗</a></div></details></article>)}</div><p className="service-note">Seleção inicial de atendimentos. Informações e descrições sujeitas à validação da clínica.</p></section>
<section className="manifesto"><span className="eyebrow">NOSSA RAZÃO DE ESTAR AQUI</span><h2>Cuidar é estar perto.<br/><em>Em cada fase.</em><br/>Em cada recomeço.</h2><span className="manifesto-star" aria-hidden="true">✳</span><p>CLÍNICA SÃO LUCAS · BELÉM DE SÃO FRANCISCO</p></section>
<section className="team section" id="profissionais"><Label n="03" title="PROFISSIONAIS" aside="QUEM CUIDA DE VOCÊ"/><div className="team-grid"><h2>Muitos olhares.<br/><em>Um cuidado<br/>mais próximo.</em></h2><div className="team-copy"><p>Conheça os profissionais apresentados pela Clínica São Lucas.</p><div className="team-reserved"><span>NOSSA EQUIPE</span><p>As pessoas por trás<br/>de cada cuidado.</p><small>Consulte a clínica para confirmar a disponibilidade dos atendimentos.</small></div></div></div><div className="professionals-grid">{professionals.map(person=><figure className="professional" key={person.id}><div className="professional-photo"><img src={'/profissionais/'+person.id+'.webp'} alt={person.name} width="150" height="130" loading="lazy"/></div><figcaption><h3>{person.name}</h3><p>{person.area}</p></figcaption></figure>)}</div></section>
<section className="contact section" id="contato"><Label n="04" title="CONTATO" aside="VAMOS CONVERSAR"/><div className="contact-grid"><div><h2>Seu próximo passo<br/>começa com uma<br/><em>boa conversa.</em></h2><p>Informações sobre atendimentos e agendamentos<br/>com a equipe da Clínica São Lucas.</p><div className="contact-pending">WhatsApp <span>↗</span><small>[NÚMERO DA CLÍNICA A CONFIRMAR]</small></div></div><div className="contact-info"><div><span>ONDE ESTAMOS</span><h3>Belém de São Francisco — PE</h3><p>[ENDEREÇO COMPLETO DA CLÍNICA]</p></div><div><span>HORÁRIOS</span><p>[HORÁRIO DE FUNCIONAMENTO]</p></div><div><span>ACOMPANHE A CLÍNICA</span><p>Instagram · [PERFIL OFICIAL]</p></div><small>Os canais de contato serão ativados após a confirmação dos dados.</small></div></div></section></main>
<footer><Brand/><p>Cuidar de você. Perto de você.</p><a href="#inicio">Voltar ao topo ↑</a><div className="footer-bottom"><span>© 2026 Clínica São Lucas.</span><span>PRIMEIRA VERSÃO · CONTEÚDO EM VALIDAÇÃO</span></div></footer></>}
