"use client";
import { useState } from 'react';
import './opening.css';
import './surgical-updates.css';
import './icons.css';
import { agendaProfessionals } from './agenda/agenda-professionals';
import { WeeklySchedule } from './agenda/WeeklySchedule';
import { assetUrl } from './asset-url';
import { Icon } from './Icon';
function Brand(){return <a className="brand" href="#inicio" aria-label="Clínica São Lucas — início"><img src={assetUrl('/logo-original.jpg')} alt="" width="52" height="52"/><span><small>CLÍNICA</small><strong>SÃO LUCAS</strong></span></a>}
function Label({n,title,aside}:{n:string,title:string,aside:string}){return <div className="section-label"><span>{n} / {title}</span><span>{aside}</span></div>}
export default function Home(){const [menu,setMenu]=useState(false);const [showAllProfessionals,setShowAllProfessionals]=useState(false);const visibleProfessionals=showAllProfessionals?agendaProfessionals:agendaProfessionals.slice(0,10);return <>
<a className="skip" href="#conteudo">Pular para o conteúdo</a><header className="site-header"><a className="brand brand-clean" href="#inicio" aria-label="Clínica São Lucas — início"><svg viewBox="0 0 72 100" width="48" height="66" aria-hidden="true"><defs><linearGradient id="brand-blue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#17285f"/><stop offset=".68" stopColor="#20366f"/><stop offset="1" stopColor="#0788ad"/></linearGradient></defs><g fill="none" strokeWidth="4"><path stroke="url(#brand-blue)" d="M34 5C5 23 5 49 23 65M43 10C17 27 17 48 32 62M52 15C29 30 29 48 41 60"/><path stroke="#d1843f" d="M38 95C67 77 67 51 49 35M29 90C55 73 55 52 40 38M20 85C43 70 43 52 31 40"/></g></svg><span><small>CLÍNICA</small><strong>SÃO LUCAS</strong></span></a><nav id="navigation" aria-label="Navegação principal" className={menu?'open':''}>{[['A clínica','clinica'],['Atendimentos','atendimentos'],['Profissionais','profissionais']].map(([text,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{text}</a>)}<a className="nav-contact" href="#contato" onClick={()=>setMenu(false)}>Fale conosco <span><Icon name="arrow-up-right"/></span></a></nav><button className="menu-toggle" aria-controls="navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Fechar −':'Menu +'}</button></header>
<main id="conteudo"><section className="hero" id="inicio"><div className="hero-top"><span className="eyebrow">BELÉM DE SÃO FRANCISCO · PE</span><span className="edition">Saúde com presença.</span></div><div className="hero-content"><div className="hero-copy"><h1>Saúde,<br/>confiança e<br/><em>acolhimento!</em></h1><p>Diferentes especialidades. Um mesmo propósito:<br className="desktop-break"/> cuidar de você, mais perto de casa.</p><a className="button" href="#atendimentos">Conheça nossos atendimentos <span><Icon name="arrow-up-right"/></span></a></div><figure className="clinic-feature"><div className="clinic-feature-image"><img src={assetUrl('/clinica-hero-real.webp')} alt="Fachada da Clínica São Lucas" width="1280" height="960" fetchPriority="high"/></div></figure></div><div className="hero-bottom"><a href="#clinica">Conheça a clínica <span><Icon name="arrow-down"/></span></a><span>Ciência. Escuta. Cuidado.</span></div></section>
<div className="ribbon"><span>Saúde em cada fase da vida</span><i><Icon name="spark"/></i><span>Cuidado que conecta</span><i><Icon name="spark"/></i><span>Clínica São Lucas</span><i><Icon name="spark"/></i><span>Saúde em cada fase da vida</span></div>
<section className="about section" id="clinica"><Label n="01" title="A CLÍNICA" aside="PERTO DE VOCÊ"/><div className="about-grid"><div className="photo-placeholder clinic-front-photo"><img src={assetUrl('/clinica-fachada-about.jpg')} alt="Fachada da Clínica São Lucas" width="1280" height="960" loading="lazy" decoding="async"/></div><div className="about-copy"><h2>Antes de tudo,<br/>olhamos para<br/><em>você.</em></h2><p>A Clínica São Lucas está em Belém de São Francisco, Pernambuco. Aqui, diferentes áreas da saúde se encontram em um só lugar.</p><p className="provisional">Cada pessoa merece ser acolhida com atenção,<br className="desktop-break"/> escuta e cuidado em cada etapa da sua saúde.</p><a className="text-link" href="#contato">Vamos conversar <span><Icon name="arrow-up-right"/></span></a></div></div></section>
<WeeklySchedule professionals={agendaProfessionals}/>
<section className="manifesto"><span className="eyebrow">NOSSA RAZÃO DE ESTAR AQUI</span><h2>Cuidar é estar perto.<br/><em>Em cada fase.</em><br/>Em cada recomeço.</h2><span className="manifesto-star" aria-hidden="true"><Icon name="spark"/></span><p>CLÍNICA SÃO LUCAS · BELÉM DE SÃO FRANCISCO</p></section>
<section className="team section" id="profissionais"><Label n="03" title="PROFISSIONAIS" aside="QUEM CUIDA DE VOCÊ"/><div className="team-grid"><h2>Muitos olhares.<br/><em>Um cuidado<br/>mais próximo.</em></h2><div className="team-copy"><p>Conheça os profissionais apresentados pela Clínica São Lucas.</p><div className="team-reserved"><span>NOSSA EQUIPE</span><p>As pessoas por trás<br/>de cada cuidado.</p><small>Consulte a clínica para confirmar a disponibilidade dos atendimentos.</small></div></div></div><div className="professionals-grid">{visibleProfessionals.map(person=><figure className="professional" key={person.id}><div className="professional-photo"><img src={assetUrl(person.photo ?? `/profissionais/${person.id}.webp`)} alt={person.name} width="150" height="130" loading="lazy" decoding="async"/></div><figcaption><h3>{person.name}</h3><p>{person.area}</p></figcaption></figure>)}</div><button className="team-more" type="button" aria-expanded={showAllProfessionals} onClick={()=>setShowAllProfessionals(!showAllProfessionals)}>{showAllProfessionals?'Ver menos':'Ver mais'} <span><Icon name={showAllProfessionals?'arrow-up':'arrow-down'}/></span></button></section>
<section className="contact section" id="contato"><Label n="04" title="CONTATO" aside="VAMOS CONVERSAR"/><div className="contact-grid"><div><h2>Seu próximo passo<br/>começa com uma<br/><em>boa conversa.</em></h2><p>Informações sobre atendimentos e agendamentos<br/>com a equipe da Clínica São Lucas.</p><a className="contact-pending" href="https://api.whatsapp.com/send?phone=5587999156764" target="_blank" rel="noopener noreferrer">WhatsApp <span><Icon name="arrow-up-right"/></span><small>+55 (87) 99915-6764</small></a></div><div className="contact-info"><div><span>ONDE ESTAMOS</span><h3>Belém de São Francisco — PE</h3><p><a href="https://www.google.com/maps/search/?api=1&amp;query=Av.%20Cel.%20Jer%C3%B4nimo%20P%C3%ADres%2C%20Centro%2C%20Bel%C3%A9m%20do%20S%C3%A3o%20Francisco%20-%20PE%2C%2056440-000" target="_blank" rel="noopener noreferrer">Av. Cel. Jerônimo Píres — Centro<br/>Belém do São Francisco — PE<br/>56440-000 <Icon name="arrow-up-right" className="inline-icon"/></a></p></div><div><span>HORÁRIOS</span><p>Segunda a sexta · 07:00–17:00<br/>Sábado · 07:00–11:00<br/>Domingo · Fechado</p></div><div><span>ACOMPANHE A CLÍNICA</span><p><a href="https://www.instagram.com/clinicasaolucasbelem/" target="_blank" rel="noopener noreferrer">Instagram · @clinicasaolucasbelem <Icon name="arrow-up-right" className="inline-icon"/></a></p></div></div></div></section></main>
<footer><Brand/><p>Cuidar de você. Perto de você.</p><a href="#inicio">Voltar ao topo <Icon name="arrow-up" className="inline-icon"/></a><div className="footer-bottom"><span>© 2026 Clínica São Lucas.</span><span>RESP. TÉC.: DR. ALEXANDRE TORRES CADEIA · CRM 18725</span></div></footer></>}
